{% set name = "caio" %}
{% set version = "0.9.20" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/caio-{{ version }}.tar.gz
  sha256: cf6b7392f797bb32e539f7acb4d8f38ae69a6d2dadf3dcda3eea5f27c9fe08a8

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python  # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools >=42
  run:
    - python

test:
  imports:
    - caio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mosquito/caio
  summary: Asynchronous file IO for Linux Posix and Windows.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
    - matthewfeickert
