{% set name = "caio" %}
{% set version = "0.9.19" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/caio-{{ version }}.tar.gz
  sha256: bdcb529330730c4c364b79789620f33bafad8c2c854c1205ecc2d16511c0b690

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  # OSX does not support fdatasync
  skip: true  # [py<36 or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - caio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mosquito/caio
  summary: Asynchronous file IO for Linux Posix and Windows.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
