{% set name = "caio" %}
{% set version = "0.9.19" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/caio-{{ version }}.tar.gz
  sha256: bdcb529330730c4c364b79789620f33bafad8c2c854c1205ecc2d16511c0b690

build:
  number: 1
  script:
    # FIXME: Avoid 'ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]' error on osx builds
    - export CFLAGS="$CFLAGS -Wno-implicit-function-declaration"  # [osx and x86]
    - {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - pip
    - python
    - setuptools >=42
  run:
    - python

test:
  imports:
    - caio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mosquito/caio
  summary: Asynchronous file IO for Linux Posix and Windows.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
