{% set name = "caio" %}
{% set version = "0.9.17" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/caio-{{ version }}.tar.gz
  sha256: 8f30511526814d961aeef389ea6885273abe6c655f1e08abbadb95d12fdd9b4f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - caio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mosquito/caio
  summary: Asynchronous file IO for Linux Posix and Windows.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
