schema_version: 1

context:
  version: "0.12.4"

package:
  name: caio
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/caio/caio-${{ version }}.tar.gz
  sha256: 32d8e9f3e2099c8db29446679252766c9bcd806eb88b4fb60ad274f73df2a5e9

build:
  number: 0
  script:
    - ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - python
  host:
    - pip
    - python
    - setuptools >=77
  run:
    - python

tests:
  - python:
      imports:
        - caio
      pip_check: true

about:
  summary: Asynchronous file IO for Linux Posix and Windows.
  license: Apache-2.0
  license_file: COPYING
  homepage: https://github.com/mosquito/caio

extra:
  recipe-maintainers:
    - thewchan
    - matthewfeickert
